# Generated by Django 4.1.7 on 2023-05-20 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vo", "Voice Over"),
                            ("bg_music", "Background Music"),
                            ("video_music", "Video Music "),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "high_volume",
                    models.PositiveIntegerField(
                        help_text="volume when this element is not overlapping with other audio element.",
                        verbose_name="High Volume",
                    ),
                ),
                (
                    "low_volume",
                    models.PositiveIntegerField(
                        help_text="volume when this element is overlapping with other audio element.",
                        verbose_name="Low Volume",
                    ),
                ),
                (
                    "video_component_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="video-component-id if type is video_music else null.",
                        null=True,
                        verbose_name="Video Component ID",
                    ),
                ),
                (
                    "url",
                    models.FileField(
                        blank=True,
                        help_text="video-component-id if type is video_music else null.",
                        null=True,
                        upload_to="audios/",
                        verbose_name="Audio File",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Audios",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="AudioDuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.PositiveIntegerField()),
                ("end_time", models.PositiveIntegerField()),
                (
                    "audio_element",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duration",
                        to="app.audio",
                    ),
                ),
            ],
        ),
    ]
